version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  gcp-gke: circleci/gcp-gke@1.4.0
  gh: circleci/github-cli@2.1.0

jobs:
  build-push-job:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
         version: 19.03.13         
      - gcp-gcr/build-image:
          docker-context: .
          dockerfile: Dockerfile
          google-project-id: GOOGLE_PROJECT_ID
          image: aman1-test/test
          registry-url: "asia-south1-docker.pkg.dev"
          path: . 
          tag: latest
          
         
      - gcloud/install
      
      - run:
          name: AR authorization
          command: gcloud auth configure-docker\asia-south1-docker.pkg.dev
          
      - gcp-gcr/push-image:
          registry-url: "asia-south1-docker.pkg.dev"
          image: aman1-test/test
          google-project-id: GOOGLE_PROJECT_ID
          tag: latest     
    
workflows:  
  workflow-build-push-image-aman:    
    jobs:
      - build-push-job:
          filters:
            branches:
              only:
                - main
          context: test-ci
