version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  gcp-gke: circleci/gcp-gke@1.4.0
  gh: circleci/github-cli@2.1.0
  gcloud: circleci/gcp-cli@2.4.0
  k8s: circleci/kubernetes@1.3.0

jobs:
  build-push-job:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
         version: 19.03.13

      - run:
          name: pushing image
          command: |
            docker build -t asia-south1-docker.pkg.dev/$GCP_PROJECT_ID1/aman1-test/w:<<pipeline.number>> .
            echo $GCP_PROJECT_KEY | docker login -u _json_key --password-stdin \asia-south1-docker.pkg.dev
            docker push asia-south1-docker.pkg.dev/$GCP_PROJECT_ID1/aman1-test/w:<<pipeline.number>>    
         
  deploy_to_prod:
    environment:
      DOCKER_IMAGE: asia-south1-docker.pkg.dev/$GCP_PROJECT_ID1/aman1-test/w:<<pipeline.number>>

    docker:
      - image: cimg/base:2022.01

    steps:
      - checkout
      - k8s/install-kubectl
      - gcloud/install
      - run:
          name: Deploy to Prod cluster
          command: |
            echo $GCP_PROJECT_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project $GCP_PROJECT_ID1
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud container clusters get-credentials $PROD_CLUSTER_NAME --zone $GOOGLE_COMPUTE_ZONE --project $GCP_PROJECT_ID1
            cd ~/project/scripts
            sh K8s-generator.sh prod $DOCKER_IMAGE
            cat Deployment.yaml
            kubectl apply -f Deployment.yaml
            
workflows:  
  workflow-build-push-image-aman:    
    jobs:
      - build-push-job:
          filters:
            branches:
              only:
                - main
          context: test-ci
      - deploy_to_prod:
          filters:
            branches:
              only:
                - main
          context: test-ci
          requires:
            - build-push-job
