version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  gcp-gke: circleci/gcp-gke@1.4.0
  gh: circleci/github-cli@2.1.0
  gcloud: circleci/gcp-cli@2.4.0

jobs:
  build-push-job:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
         version: 19.03.13

      - run:
          name: pushing image
          command: |
            docker build -t asia-south1-docker.pkg.dev/$GCP_PROJECT_ID1/aman1-test/w .
            
            echo $GCP_PROJECT_KEY | docker login -u _json_key --password-stdin \asia-south1-docker.pkg.dev
            
            docker push asia-south1-docker.pkg.dev/$GCP_PROJECT_ID1/aman1-test/w    
        
    
workflows:  
  workflow-build-push-image-aman:    
    jobs:
      - build-push-job:
          filters:
            branches:
              only:
                - main
          context: test-ci
