version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  gcp-gke: circleci/gcp-gke@1.4.0
  gh: circleci/github-cli@2.1.0
  gcloud: circleci/gcp-cli@2.4.0

jobs:
  build-push-job:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
         version: 19.03.13

      - run:
          name: building image
          command: docker build --tag asia-south1-docker.pkg.dev/$GOOGLE_PROJECT_ID/aman1-test/test1:v1 .

      - gcloud/install
      
      - run:
          name: pushing the image
          command: docker push asia-south1-docker.pkg.dev/$GOOGLE_PROJECT_ID/aman1-test/test1:latest         
   
    
workflows:  
  workflow-build-push-image-aman:    
    jobs:
      - build-push-job:
          filters:
            branches:
              only:
                - main
          context: test-ci
